### ISSUE TITLE
Support for Regula 1120 device is not available 

### ISSUE THREAD

**Issue by JawadUsman1** [regulaforensics/DocumentReader-Android#25]
Hi Team,

I'm unable to find any documentation or SDK for the Regula 1120 device SDK versions 5.2.

**Comment by markomaxo** [comment]
![image](https://user-images.githubusercontent.com/58534833/94022293-d94b1480-fdac-11ea-9fa8-fb5190f01ed5.png)
what i can do with this problem?

**Comment by vyakimchik** [comment]
Hi. Use the project that is available in the `develop` branch, rather than in the `master` one as the SDK for Flutter hasn't been released yet. Also, please note that there is no SDK yet that supports working with the device Regula 1120.

Link: https://github.com/regulaforensics/DocumentReader-Flutter/tree/develop.
