### ISSUE TITLE
resources.dat in assets making huge size impact in apk

### ISSUE THREAD

**Issue by thasneemp** [regulaforensics/DocumentReader-Android#5]
In APK the 49% of resource is coming from Regula in assets folder seems Regula/resources.dat 41MB size
how to reduce that much size

**Comment by mskvorcovs** [comment]
Hello,
The assets folder contains document description database, which is necessary for document type recognition and allows to perform OCR of the document text.

The size might be reduced by building a custom database, which contains only your required documents instead of all documents. The database can be omitted in case MRZ or Barcode reading is enough.

Please, contact us at support@regulaforensics.com and tell us about your workflow scenario.
